title:              Exot.icu
email:              brunashantaram97@gmail.com
description:        "Eu não tenho filosofia tenho sentidos...
                    Se falo na Natureza não é porque eu saiba o que ela é.
                    Mas porque a amo, e amo-a por isso.
                    Porque quem ama nunca sabe o que é amar.
                    Nem por que ama, nem o que é amar."
author:             B. Shantaram
baseurl:            "/"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
